# Generated by Django 3.0 on 2021-05-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='man.png', upload_to='profile_picture')),
                ('bio', models.CharField(blank=True, max_length=300, null=True)),
                ('hide_email', models.BooleanField(default=True)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('work', models.CharField(blank=True, max_length=500, null=True)),
                ('loaction', models.CharField(blank=True, max_length=100, null=True)),
                ('educations', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
