# Generated by Django 3.1.7 on 2021-04-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followers',
            new_name='following',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
