# Generated by Django 3.1.7 on 2021-04-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210401_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='following',
            new_name='followers',
        ),
    ]
