# Generated by Django 3.0 on 2021-05-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
