# Generated by Django 3.1.7 on 2021-03-25 18:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0002_auto_20210317_0140'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Answer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
